[package]
name = "mora-storage"
version = "0.0.0"
edition = "2021"

[dependencies]
mora-core = { workspace = true }
log = { workspace = true }
rmp-serde = { workspace = true }
fsst-rs = { workspace = true }
crc32fast = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
